#!/bin/sh

stagedJsFiles=$(git diff --cached --name-only --diff-filter=ACMRTUB | grep '\.js')
echo "stagedJsFiles='${stagedJsFiles}'"

if [ -z "$stagedJsFiles" ] ; then
 exit 0
fi

./node_modules/.bin/prettier --write $stagedJsFiles
git add $stagedJsFiles

./node_modules/.bin/eslint $stagedJsFiles

exit $?

