#!/bin/sh

if [ $# -ne 1 ]; then
    # normal/simple commits provide only one argument
    # with more arguments we just skip the hook
    exit 0
fi 

# save the name of the file with the default message
commitEditMsgFile=$1

# store the original content of the file
originalFileContent=$(cat $commitEditMsgFile)

# overriding the content of the file
echo "task-????: ?????" > $commitEditMsgFile
echo "" >> $commitEditMsgFile
echo "# The format we require for our commits is:" >> $commitEditMsgFile
echo "#\ttask-{4 digits number}: small description of changes [min 5, max 30 characters]" >> $commitEditMsgFile

# appending the original content (of course this is optional)
echo "$originalFileContent" >> $commitEditMsgFile

# Here is for some reason we want to abort the commit
# we can still exit with a non-zero code:
# exit 1

